In [1]:
from riken.rnn.rnn_keras_with_psiblast import *

RANDOM_STATE = 42
MAXLEN = 500
DATA_PATH = "/home/pierre/riken/data/riken_data/complete_from_xlsx.tsv"
KEY_TO_PREDICT = "is_allergenic"
LOG_DIR = "/home/pierre/riken/riken/rnn/logs/riken_data_psiblast/logs_riken_data_psiblast_1_transfer"
TRANSFER_PATH = None
GROUPS = "species"
SPLITTER = data_op.group_shuffle_indices
PSSM_FORMAT_FILE = "/home/pierre/psiblast/riken_data/{}_pssm.txt"

Using TensorFlow backend.


In [2]:
df = pd.read_csv(DATA_PATH, sep='\t').dropna()
df = df.loc[df.seq_len >= 50, :]

try:
    df.loc[:, 'sequences'] = df.sequences_x
except AttributeError:
    pass

sequences, y = df['sequences'].values, df[KEY_TO_PREDICT]
y = pd.get_dummies(y).values
X = pad_sequences([[prot_features.safe_char_to_idx(char) for char in sequence]
                   for sequence in sequences], maxlen=MAXLEN)
groups = None if GROUPS is None else df[GROUPS].values
indices = df.index.values

# Get train test indices before getting all features (potentially less
# FOR CONSISTENCY PURPOSES
train_inds, test_inds = SPLITTER(sequences, y, groups)

X, pssm, y, old_to_new_indices = get_all_features(X, y, indices, pssm_format_fi=PSSM_FORMAT_FILE)

def convert_indices(old_to_new_dic, indices):
    res_ind = []
    for ind in indices:
        if ind in old_to_new_dic:
            res_ind.append(old_to_new_dic[ind])
    return np.array(res_ind)

train_inds = convert_indices(old_to_new_indices, train_inds)
test_inds = convert_indices(old_to_new_indices, test_inds)
print(np.intersect1d(train_inds, test_inds))
assert len(np.intersect1d(train_inds, test_inds)) == 0
print(train_inds.shape, test_inds.shape)
Xtrain, Xtest, ytrain, ytest = X[train_inds], X[test_inds], y[train_inds], y[test_inds]
pssm_train, pssm_test = pssm[train_inds], pssm[test_inds]

print(pssm_train[0])
print(pssm_test[0])


  0%|          | 0/12466 [00:00<?, ?it/s]/home/pierre/riken/riken/rnn/rnn_keras_with_psiblast.py:42: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  pssm = pd.read_csv(pssm_path, sep=' ', skiprows=2, skipfooter=6, skipinitialspace=True)\
  3%|▎         | 370/12466 [00:12<06:57, 28.95it/s]

[Errno 2] No such file or directory: '/home/pierre/psiblast/riken_data/397_pssm.txt'
Error!


  4%|▍         | 536/12466 [00:16<06:14, 31.83it/s]

[Errno 2] No such file or directory: '/home/pierre/psiblast/riken_data/577_pssm.txt'
Error!


  4%|▍         | 558/12466 [00:17<06:13, 31.87it/s]

[Errno 2] No such file or directory: '/home/pierre/psiblast/riken_data/594_pssm.txt'
Error!


  5%|▌         | 631/12466 [00:19<05:59, 32.93it/s]

[Errno 2] No such file or directory: '/home/pierre/psiblast/riken_data/669_pssm.txt'
Error!


  6%|▌         | 772/12466 [00:22<05:47, 33.62it/s]

[Errno 2] No such file or directory: '/home/pierre/psiblast/riken_data/809_pssm.txt'
Error!


  6%|▋         | 798/12466 [00:23<05:44, 33.86it/s]

[Errno 2] No such file or directory: '/home/pierre/psiblast/riken_data/833_pssm.txt'
Error!


  7%|▋         | 929/12466 [00:26<05:31, 34.76it/s]

[Errno 2] No such file or directory: '/home/pierre/psiblast/riken_data/972_pssm.txt'
Error!


  9%|▉         | 1118/12466 [00:31<05:19, 35.54it/s]

[Errno 2] No such file or directory: '/home/pierre/psiblast/riken_data/1168_pssm.txt'
Error!


 10%|█         | 1281/12466 [00:35<05:10, 36.04it/s]

[Errno 2] No such file or directory: '/home/pierre/psiblast/riken_data/1346_pssm.txt'
Error!


 11%|█▏        | 1432/12466 [00:38<04:59, 36.78it/s]

[Errno 2] No such file or directory: '/home/pierre/psiblast/riken_data/1499_pssm.txt'
Error!


 12%|█▏        | 1480/12466 [00:40<04:57, 36.98it/s]

[Errno 2] No such file or directory: '/home/pierre/psiblast/riken_data/1547_pssm.txt'
Error!


 12%|█▏        | 1549/12466 [00:41<04:52, 37.29it/s]

[Errno 2] No such file or directory: '/home/pierre/psiblast/riken_data/1617_pssm.txt'
Error!


 13%|█▎        | 1566/12466 [00:41<04:51, 37.34it/s]

[Errno 2] No such file or directory: '/home/pierre/psiblast/riken_data/1631_pssm.txt'
Error!


 14%|█▎        | 1693/12466 [00:44<04:44, 37.81it/s]

[Errno 2] No such file or directory: '/home/pierre/psiblast/riken_data/1758_pssm.txt'
Error!
[Errno 2] No such file or directory: '/home/pierre/psiblast/riken_data/1759_pssm.txt'
Error!
[Errno 2] No such file or directory: '/home/pierre/psiblast/riken_data/1760_pssm.txt'
Error!
[Errno 2] No such file or directory: '/home/pierre/psiblast/riken_data/1768_pssm.txt'
Error!


 14%|█▍        | 1774/12466 [00:46<04:40, 38.13it/s]

[Errno 2] No such file or directory: '/home/pierre/psiblast/riken_data/1839_pssm.txt'
Error!
[Errno 2] No such file or directory: '/home/pierre/psiblast/riken_data/1840_pssm.txt'
Error!
[Errno 2] No such file or directory: '/home/pierre/psiblast/riken_data/1841_pssm.txt'
Error!
[Errno 2] No such file or directory: '/home/pierre/psiblast/riken_data/1842_pssm.txt'
Error!
[Errno 2] No such file or directory: '/home/pierre/psiblast/riken_data/1843_pssm.txt'
Error!
[Errno 2] No such file or directory: '/home/pierre/psiblast/riken_data/1844_pssm.txt'
Error!
[Errno 2] No such file or directory: '/home/pierre/psiblast/riken_data/1855_pssm.txt'
Error!


 15%|█▌        | 1875/12466 [00:49<04:37, 38.23it/s]

[Errno 2] No such file or directory: '/home/pierre/psiblast/riken_data/1950_pssm.txt'
Error!
[Errno 2] No such file or directory: '/home/pierre/psiblast/riken_data/1960_pssm.txt'
Error!


 15%|█▌        | 1891/12466 [00:49<04:36, 38.22it/s]

[Errno 2] No such file or directory: '/home/pierre/psiblast/riken_data/1972_pssm.txt'
Error!


100%|██████████| 12466/12466 [06:08<00:00, 33.81it/s]


(12439, 500)
(12439, 2)
(12439, 500, 42)
12439 examples
[]
(10814,) (1248,)
[[ 0.    0.    0.   ...  0.    0.    0.  ]
 [ 0.    0.    0.   ...  0.    0.    0.  ]
 [ 0.    0.    0.   ...  0.    0.    0.  ]
 ...
 [ 3.   -4.   -4.   ...  0.    1.62  0.36]
 [-2.   -1.   -2.   ... 15.    0.33  0.16]
 [-3.   -4.   -5.   ... 40.    0.85  0.28]]
[[ 0.    0.    0.   ...  0.    0.    0.  ]
 [ 0.    0.    0.   ...  0.    0.    0.  ]
 [ 0.    0.    0.   ...  0.    0.    0.  ]
 ...
 [-1.   -2.    2.   ...  0.    0.55  0.14]
 [-2.   -1.    1.   ...  0.    0.98  0.23]
 [-2.   -2.   -3.   ...  0.    1.9   0.2 ]]


In [4]:
from keras.models import load_model

mdl = load_model('logs/riken_data_psiblast/logs_riken_data_psiblast_1_transfer/weights.12-0.35.hdf5')

ypred = mdl.predict([Xtest, pssm_test])

In [8]:
test_df = df.iloc[test_inds]
test_df.loc[:, 'y_pred'] = ypred[:, 1]

/home/pierre/.conda/envs/python3/lib/python3.6/site-packages/pandas/core/indexing.py:362: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[key] = _infer_fill_value(value)
/home/pierre/.conda/envs/python3/lib/python3.6/site-packages/pandas/core/indexing.py:543: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


In [12]:
from sklearn.metrics import roc_auc_score

def roc_auc(df):
    return roc_auc_score(df.is_allergenic, df.y_pred)

is_long = test_df.seq_len >= 500
test_df.groupby(is_long).apply(roc_auc)

seq_len
False    0.932053
True     0.914596
dtype: float64

In [14]:
is_long.sum()

193

In [15]:
test_df[is_long].seq_len.describe()

count     193.000000
mean      719.119171
std       345.191238
min       500.000000
25%       527.000000
50%       608.000000
75%       796.000000
max      3099.000000
Name: seq_len, dtype: float64